name: 📝 Draft or update next release
concurrency: draft_or_update_next_release

on:
  push:
    branches:
      - main

env:
  CI: true
  NODE_VERSION: 14

jobs:
  prepare-deployment:
    name: 📝 Draft or update next release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?!v[0-9]).*'
          flags: 'gm'
          error: 'Skip draft release on new versions'
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
